site_name: MLTE Documentation
theme:
  name: "material"
  palette:
    scheme: slate
  logo: https://raw.githubusercontent.com/mlte-team/mlte/master/assets/MLTE_Logo_Color.svg
  #favicon: mlte_favicon.ico
watch:
  - ../src/mlte
plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [../src]
          options:
            docstring_style: sphinx
  - gen-files:
      scripts:
        - tools/generate_ref_pages.py
  - literate-nav:
      nav_file: SUMMARY.md
nav:
  - Home: 'index.md'
  - 'How-to Guides':
    - 'Getting Started': 'getting_started.md'
    - 'Development': 'development.md'
  - 'Tutorials':
    - 'Testing a Model with MLTE': 'tutorial0.md'
  - 'References':
    - 'MLTE Framework': 'mlte_framework.md'
    - API Reference: reference/
  - 'Explanations':
    - 'MLTE Process Resources': 'explanation1.md'
